# Generated by Django 5.0.4 on 2024-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_spraying_operation', models.BooleanField(default=True)),
                ('is_spraying_operation_off', models.BooleanField(default=False)),
                ('is_home_setpoint', models.BooleanField(default=True)),
                ('is_home_setpoint_off', models.BooleanField(default=False)),
                ('is_emergency_droneland', models.BooleanField(default=True)),
                ('is_emergency_droneland_off', models.BooleanField(default=False)),
                ('is_drone_connected', models.BooleanField(default=True)),
                ('is_drone_disconnected', models.BooleanField(default=False)),
            ],
        ),
    ]
