# Generated by Django 5.0.4 on 2024-04-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneserver',
            name='title',
            field=models.CharField(default='RIFM Controllers', max_length=50),
        ),
    ]
